"""Multi-vehicle, multi-order route planning engine.

Pure standard-library so it can be unit-tested without Flask/Mongo/Torch.

What it supports
----------------
* many pickups and many drop-offs per vehicle, with pickup-before-delivery
  precedence kept valid at every step;
* orders that are simply loaded at the depot (delivery-only) as well as true
  pickup->delivery jobs;
* custom stops (rest, break, fuel, arbitrary waypoints) with their own service
  time, plus automatic driving-hours breaks;
* weight / volume / pallet capacity per vehicle;
* time windows (arrive early -> wait, arrive late -> flagged);
* empty-running measurement, including the repositioning leg from a vehicle's
  start location to its first pickup;
* a locked sequence mode so a planner can hand-order the stops and still get
  costed, validated output.

The optimiser is a cheapest-insertion construction followed by or-opt / 2-opt
local search. That is the standard practical approach for pickup-and-delivery
problems of this size and it keeps the runtime well inside a web request.
"""
import time
from dataclasses import dataclass, field, replace
from typing import Callable, Dict, List, Optional, Tuple

from config import Config
from geo import km_to_miles, leg_metrics, road_distance_km, travel_minutes

# --------------------------------------------------------------------------
# Value objects
# --------------------------------------------------------------------------


@dataclass
class Stop:
    key: str
    type: str                      # pickup | delivery | rest | break | fuel | custom
    name: str
    lat: float
    lon: float
    service_minutes: float = 0.0
    order_id: Optional[str] = None
    order_ref: Optional[str] = None
    location_id: Optional[str] = None
    weight_kg: float = 0.0         # signed: + on pickup, - on delivery
    volume_m3: float = 0.0
    pallets: int = 0
    window_start: Optional[int] = None   # minutes from midnight
    window_end: Optional[int] = None
    address: str = ''
    notes: str = ''
    contact: str = ''
    packages: List[dict] = field(default_factory=list)
    vehicle_id: Optional[str] = None     # pre-assignment / lock
    auto: bool = False                   # generated by the engine (driver breaks)
    sequence: int = 0                    # position in the request (locked mode)

    def to_dict(self):
        return {
            'key': self.key,
            'type': self.type,
            'name': self.name,
            'lat': self.lat,
            'lon': self.lon,
            'service_minutes': round(self.service_minutes, 1),
            'order_id': self.order_id,
            'order_ref': self.order_ref,
            'location_id': self.location_id,
            'weight_kg': round(self.weight_kg, 2),
            'volume_m3': round(self.volume_m3, 3),
            'pallets': self.pallets,
            'window_start': minutes_to_hhmm(self.window_start),
            'window_end': minutes_to_hhmm(self.window_end),
            'address': self.address,
            'notes': self.notes,
            'contact': self.contact,
            'packages': self.packages,
            'auto': self.auto,
        }


def stop_from_dict(data: dict) -> 'Stop':
    """Rebuild a Stop from its serialised form (used when re-costing a saved plan)."""
    return Stop(
        key=data.get('key') or f"stop-{data.get('name', '')}",
        type=data.get('type', 'custom'),
        name=data.get('name', 'Stop'),
        lat=float(data['lat']), lon=float(data['lon']),
        service_minutes=float(data.get('service_minutes') or 0),
        order_id=data.get('order_id'),
        order_ref=data.get('order_ref'),
        location_id=data.get('location_id'),
        weight_kg=float(data.get('weight_kg') or 0),
        volume_m3=float(data.get('volume_m3') or 0),
        pallets=int(data.get('pallets') or 0),
        window_start=hhmm_to_minutes(data.get('window_start')),
        window_end=hhmm_to_minutes(data.get('window_end')),
        address=data.get('address', ''),
        notes=data.get('notes', ''),
        contact=data.get('contact', ''),
        packages=data.get('packages') or [],
        auto=bool(data.get('auto')),
    )


@dataclass
class Job:
    """One order: a pickup, a delivery, or both.

    * pickup + delivery — a normal collection-and-delivery job;
    * delivery only     — goods loaded at the depot before departure;
    * pickup only       — a collection brought back to base.
    """
    order_id: str
    reference: str
    delivery: Optional[Stop] = None
    pickup: Optional[Stop] = None
    weight_kg: float = 0.0
    volume_m3: float = 0.0
    pallets: int = 0
    priority: int = 3               # 1 = highest
    temperature_controlled: bool = False
    hazardous: bool = False
    vehicle_id: Optional[str] = None  # hard assignment when set

    @property
    def stops(self) -> List[Stop]:
        return [s for s in (self.pickup, self.delivery) if s is not None]


@dataclass
class Vehicle:
    id: str
    name: str
    start: Stop
    end: Optional[Stop] = None
    registration: str = ''
    type: str = 'van'
    capacity_kg: float = 1000.0
    capacity_m3: float = 10.0
    max_pallets: int = 0
    fuel_type: str = 'diesel'
    fuel_efficiency_km_per_l: float = 3.5
    kwh_per_km: float = 0.0
    co2_g_per_km: float = 0.0
    avg_speed_kmh: float = Config.DEFAULT_SPEED_KMH
    cost_per_km: float = 0.0
    cost_per_hour: float = Config.DRIVER_COST_PER_HOUR_GBP
    shift_start_min: int = 8 * 60
    max_shift_minutes: int = Config.MAX_SHIFT_MINUTES
    temperature_controlled: bool = False
    driver_id: Optional[str] = None
    driver_name: str = ''
    return_to_start: bool = True

    def cost_profile(self) -> dict:
        return {
            'fuel_type': self.fuel_type,
            'fuel_efficiency_km_per_l': self.fuel_efficiency_km_per_l,
            'kwh_per_km': self.kwh_per_km,
            'co2_g_per_km': self.co2_g_per_km,
            'cost_per_km': self.cost_per_km,
            'cost_per_hour': self.cost_per_hour,
        }


@dataclass
class PlanOptions:
    preference: str = 'greenest'          # greenest | fastest | cheapest
    optimize_sequence: bool = True        # False = respect the given order exactly
    return_to_start: bool = True
    auto_breaks: bool = True
    max_driving_minutes_before_break: int = Config.MAX_DRIVING_MINUTES_BEFORE_BREAK
    break_minutes: int = Config.DEFAULT_BREAK_MINUTES
    enforce_capacity: bool = True
    enforce_shift: bool = False           # soft by default: flag, do not reject
    road_factor: float = Config.ROAD_FACTOR
    # Search effort. The defaults keep a 40-order / 5-vehicle plan inside a
    # couple of seconds, which is what a web request can afford.
    local_search_rounds: int = 40         # passes; each applies one improving move
    insertion_width: int = 4              # positions shortlisted per pickup/drop
    verify_per_pass: int = 8              # full evaluations per improvement pass
    time_budget_seconds: float = Config.PLAN_TIME_BUDGET_SECONDS


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def hhmm_to_minutes(value) -> Optional[int]:
    """'08:30' / 510 / '510' -> 510. Returns None when unparseable."""
    if value is None or value == '':
        return None
    if isinstance(value, (int, float)):
        return int(value)
    text = str(value).strip()
    days = 0
    if '(+' in text:   # "01:00 (+1d)" — produced by minutes_to_hhmm for next-day times
        head, _, tail = text.partition('(+')
        text = head.strip()
        digits = ''.join(c for c in tail if c.isdigit())
        days = int(digits) if digits else 0
    if ':' in text:
        try:
            hours, minutes = text.split(':')[:2]
            return days * 1440 + int(hours) * 60 + int(minutes)
        except ValueError:
            return None
    try:
        return int(float(text))
    except ValueError:
        return None


def minutes_to_hhmm(value) -> Optional[str]:
    if value is None:
        return None
    value = int(round(value))
    days, rem = divmod(value, 1440)
    text = f'{rem // 60:02d}:{rem % 60:02d}'
    return f'{text} (+{days}d)' if days else text


class DistanceProvider:
    """Caches leg distances/durations, optionally via a network corridor.

    `corridor_fn(a, b)` may return `(distance_km, duration_min, via_points)` or
    `(distance_km, duration_min, via_points, shapes)` for pairs the trained road
    graph knows about; anything else falls back to the great-circle estimate
    inflated by the road factor.

    `shapes` are encoded road polylines, one per hop of the corridor, so the map
    can draw the real road rather than a straight line.
    """

    def __init__(self, road_factor=None, speed_kmh=None, corridor_fn: Optional[Callable] = None):
        self.road_factor = road_factor or Config.ROAD_FACTOR
        self.speed_kmh = speed_kmh or Config.DEFAULT_SPEED_KMH
        self.corridor_fn = corridor_fn
        self._cache: Dict[Tuple, Tuple[float, float, list, list]] = {}

    def leg(self, a: Stop, b: Stop) -> Tuple[float, float, list, list]:
        key = (round(a.lat, 5), round(a.lon, 5), round(b.lat, 5), round(b.lon, 5))
        cached = self._cache.get(key)
        if cached:
            return cached

        result = None
        if self.corridor_fn is not None:
            try:
                result = self.corridor_fn(a, b)
            except Exception:  # noqa: BLE001 - corridor is an optimisation, never fatal
                result = None
        if not result:
            distance = road_distance_km(a.lat, a.lon, b.lat, b.lon, self.road_factor)
            result = (distance, travel_minutes(distance, self.speed_kmh), [], [])

        distance, duration, via = result[0], result[1], result[2]
        shapes = result[3] if len(result) > 3 else []
        value = (float(distance), float(duration), list(via or []), list(shapes or []))
        self._cache[key] = value
        return value


# --------------------------------------------------------------------------
# Route evaluation
# --------------------------------------------------------------------------

def evaluate_route(vehicle: Vehicle, stops: List[Stop], provider: DistanceProvider,
                   options: PlanOptions) -> dict:
    """Walk a stop sequence and produce a fully costed, validated itinerary."""
    profile = vehicle.cost_profile()

    legs: List[dict] = []
    timeline: List[dict] = []
    violations: List[dict] = []

    load_kg = 0.0
    load_m3 = 0.0
    load_pallets = 0
    # Delivery-only orders are loaded at the start depot, so the vehicle leaves
    # base already carrying them.
    for stop in stops:
        if stop.type == 'delivery' and stop.weight_kg < 0 and not _has_matching_pickup(stops, stop):
            load_kg += -stop.weight_kg
            load_m3 += -stop.volume_m3
            load_pallets += stop.pallets

    start_load_kg = load_kg
    peak_load_kg = load_kg
    peak_load_m3 = load_m3

    if options.enforce_capacity and _over_capacity(vehicle, load_kg, load_m3, load_pallets):
        return _infeasible(vehicle, 'Start load exceeds vehicle capacity')

    clock = float(vehicle.shift_start_min)
    driving_since_break = 0.0
    totals = {
        'distance_km': 0.0, 'empty_km': 0.0, 'loaded_km': 0.0,
        'driving_minutes': 0.0, 'service_minutes': 0.0, 'waiting_minutes': 0.0,
        'break_minutes': 0.0, 'energy': 0.0, 'co2_kg': 0.0,
        'fuel_cost_gbp': 0.0, 'running_cost_gbp': 0.0, 'driver_cost_gbp': 0.0,
    }

    timeline.append({
        'sequence': 0, 'type': 'depot_start', 'name': vehicle.start.name,
        'lat': vehicle.start.lat, 'lon': vehicle.start.lon,
        'location_id': vehicle.start.location_id,
        'arrival': minutes_to_hhmm(clock), 'departure': minutes_to_hhmm(clock),
        'load_kg': round(load_kg, 2), 'load_m3': round(load_m3, 3),
        'service_minutes': 0, 'order_id': None, 'order_ref': None, 'auto': False,
        'address': vehicle.start.address, 'notes': '',
    })

    cursor = vehicle.start
    sequence = 0
    visited_pickups = set()

    for stop in stops:
        distance_km, duration_min, via, shapes = provider.leg(cursor, stop)

        # --- driver hours: insert a statutory break before the leg if needed
        if options.auto_breaks and driving_since_break + duration_min > options.max_driving_minutes_before_break:
            clock += options.break_minutes
            totals['break_minutes'] += options.break_minutes
            driving_since_break = 0.0
            sequence += 1
            timeline.append({
                'sequence': sequence, 'type': 'break', 'name': 'Driver break (auto)',
                'lat': cursor.lat, 'lon': cursor.lon, 'location_id': None,
                'arrival': minutes_to_hhmm(clock - options.break_minutes),
                'departure': minutes_to_hhmm(clock),
                'load_kg': round(load_kg, 2), 'load_m3': round(load_m3, 3),
                'service_minutes': options.break_minutes,
                'order_id': None, 'order_ref': None, 'auto': True,
                'address': '', 'notes': f'{options.break_minutes} min break after '
                                        f'{options.max_driving_minutes_before_break} min driving',
            })

        load_ratio = (load_kg / vehicle.capacity_kg) if vehicle.capacity_kg else 0.0
        metrics = leg_metrics(distance_km, duration_min, profile, load_ratio)
        is_empty = load_kg <= 0.001

        legs.append({
            'from': cursor.name, 'from_lat': cursor.lat, 'from_lon': cursor.lon,
            'to': stop.name, 'to_lat': stop.lat, 'to_lon': stop.lon,
            'distance_km': round(distance_km, 2),
            'distance_miles': round(km_to_miles(distance_km), 2),
            'duration_min': round(duration_min, 1),
            'empty': is_empty,
            'load_kg': round(load_kg, 2),
            'co2_kg': metrics['co2_kg'],
            'cost_gbp': metrics['total_cost_gbp'],
            'via': via,
            'shapes': shapes,
        })

        totals['distance_km'] += distance_km
        totals['driving_minutes'] += duration_min
        totals['energy'] += metrics['energy']
        totals['co2_kg'] += metrics['co2_kg']
        totals['fuel_cost_gbp'] += metrics['fuel_cost_gbp']
        totals['running_cost_gbp'] += metrics['running_cost_gbp']
        totals['driver_cost_gbp'] += metrics['driver_cost_gbp']
        totals['empty_km' if is_empty else 'loaded_km'] += distance_km

        clock += duration_min
        driving_since_break += duration_min

        arrival = clock
        waiting = 0.0
        if stop.window_start is not None and arrival < stop.window_start:
            waiting = stop.window_start - arrival
            clock = float(stop.window_start)
        late_by = 0.0
        if stop.window_end is not None and clock > stop.window_end:
            late_by = clock - stop.window_end
            violations.append({
                'type': 'time_window', 'stop': stop.name, 'order_ref': stop.order_ref,
                'message': f'Arrives {int(late_by)} min after the {minutes_to_hhmm(stop.window_end)} window closes',
            })

        service_start = clock
        clock += stop.service_minutes
        totals['service_minutes'] += stop.service_minutes
        totals['waiting_minutes'] += waiting
        if stop.type in ('rest', 'break'):
            driving_since_break = 0.0

        # --- load changes
        if stop.type == 'pickup':
            load_kg += stop.weight_kg
            load_m3 += stop.volume_m3
            load_pallets += stop.pallets
            visited_pickups.add(stop.order_id)
        elif stop.type == 'delivery':
            load_kg += stop.weight_kg          # weight_kg is negative for deliveries
            load_m3 += stop.volume_m3
            load_pallets += stop.pallets

        load_kg = 0.0 if abs(load_kg) < 1e-6 else load_kg
        load_m3 = 0.0 if abs(load_m3) < 1e-9 else load_m3
        peak_load_kg = max(peak_load_kg, load_kg)
        peak_load_m3 = max(peak_load_m3, load_m3)

        if options.enforce_capacity and _over_capacity(vehicle, load_kg, load_m3, load_pallets):
            return _infeasible(
                vehicle,
                f'Capacity exceeded at {stop.name} '
                f'({load_kg:.0f} kg / {load_m3:.1f} m³ vs {vehicle.capacity_kg:.0f} kg / {vehicle.capacity_m3:.1f} m³)'
            )

        sequence += 1
        timeline.append({
            'sequence': sequence, 'type': stop.type, 'name': stop.name,
            'lat': stop.lat, 'lon': stop.lon, 'location_id': stop.location_id,
            'arrival': minutes_to_hhmm(arrival),
            'service_start': minutes_to_hhmm(service_start),
            'departure': minutes_to_hhmm(clock),
            'waiting_minutes': round(waiting, 1),
            'late_minutes': round(late_by, 1),
            'load_kg': round(load_kg, 2), 'load_m3': round(load_m3, 3),
            'service_minutes': round(stop.service_minutes, 1),
            'order_id': stop.order_id, 'order_ref': stop.order_ref,
            'window_start': minutes_to_hhmm(stop.window_start),
            'window_end': minutes_to_hhmm(stop.window_end),
            'packages': stop.packages,
            'address': stop.address, 'notes': stop.notes, 'contact': stop.contact,
            'auto': stop.auto, 'key': stop.key,
        })
        cursor = stop

    # --- return leg
    end_stop = vehicle.end if vehicle.end else (vehicle.start if options.return_to_start and vehicle.return_to_start else None)
    if end_stop is not None and stops:
        distance_km, duration_min, via, shapes = provider.leg(cursor, end_stop)
        load_ratio = (load_kg / vehicle.capacity_kg) if vehicle.capacity_kg else 0.0
        metrics = leg_metrics(distance_km, duration_min, profile, load_ratio)
        is_empty = load_kg <= 0.001
        legs.append({
            'from': cursor.name, 'from_lat': cursor.lat, 'from_lon': cursor.lon,
            'to': end_stop.name, 'to_lat': end_stop.lat, 'to_lon': end_stop.lon,
            'distance_km': round(distance_km, 2),
            'distance_miles': round(km_to_miles(distance_km), 2),
            'duration_min': round(duration_min, 1),
            'empty': is_empty, 'load_kg': round(load_kg, 2),
            'co2_kg': metrics['co2_kg'], 'cost_gbp': metrics['total_cost_gbp'],
            'via': via, 'shapes': shapes, 'return_leg': True,
        })
        totals['distance_km'] += distance_km
        totals['driving_minutes'] += duration_min
        totals['energy'] += metrics['energy']
        totals['co2_kg'] += metrics['co2_kg']
        totals['fuel_cost_gbp'] += metrics['fuel_cost_gbp']
        totals['running_cost_gbp'] += metrics['running_cost_gbp']
        totals['driver_cost_gbp'] += metrics['driver_cost_gbp']
        totals['empty_km' if is_empty else 'loaded_km'] += distance_km
        clock += duration_min
        sequence += 1
        timeline.append({
            'sequence': sequence, 'type': 'depot_end', 'name': end_stop.name,
            'lat': end_stop.lat, 'lon': end_stop.lon, 'location_id': end_stop.location_id,
            'arrival': minutes_to_hhmm(clock), 'departure': minutes_to_hhmm(clock),
            'load_kg': round(load_kg, 2), 'load_m3': round(load_m3, 3),
            'service_minutes': 0, 'order_id': None, 'order_ref': None, 'auto': False,
            'address': end_stop.address, 'notes': '',
        })

    total_minutes = clock - vehicle.shift_start_min
    if vehicle.max_shift_minutes and total_minutes > vehicle.max_shift_minutes:
        violations.append({
            'type': 'shift_length', 'stop': None, 'order_ref': None,
            'message': f'Route takes {total_minutes / 60:.1f} h, over the '
                       f'{vehicle.max_shift_minutes / 60:.1f} h shift limit',
        })
        if options.enforce_shift:
            return _infeasible(vehicle, 'Route exceeds the maximum shift length')

    # The repositioning distance from base to the first revenue stop.
    initial_empty_km = legs[0]['distance_km'] if legs and legs[0]['empty'] else 0.0

    distance_km = totals['distance_km']
    utilisation_kg = (peak_load_kg / vehicle.capacity_kg * 100) if vehicle.capacity_kg else 0.0
    utilisation_m3 = (peak_load_m3 / vehicle.capacity_m3 * 100) if vehicle.capacity_m3 else 0.0
    total_cost = totals['fuel_cost_gbp'] + totals['running_cost_gbp'] + totals['driver_cost_gbp']

    return {
        'feasible': True,
        'vehicle_id': vehicle.id,
        'vehicle_name': vehicle.name,
        'vehicle_type': vehicle.type,
        'registration': vehicle.registration,
        'driver_id': vehicle.driver_id,
        'driver_name': vehicle.driver_name,
        'stops': [s.to_dict() for s in stops],
        'timeline': timeline,
        'legs': legs,
        'violations': violations,
        'metrics': {
            'stop_count': len([s for s in stops if s.type in ('pickup', 'delivery')]),
            'total_stops': len(stops),
            'total_distance_km': round(distance_km, 2),
            'total_distance_miles': round(km_to_miles(distance_km), 2),
            'loaded_km': round(totals['loaded_km'], 2),
            'empty_km': round(totals['empty_km'], 2),
            'empty_miles': round(km_to_miles(totals['empty_km']), 2),
            'empty_pct': round((totals['empty_km'] / distance_km * 100) if distance_km else 0.0, 1),
            'initial_empty_km': round(initial_empty_km, 2),
            'initial_empty_miles': round(km_to_miles(initial_empty_km), 2),
            'driving_minutes': round(totals['driving_minutes']),
            'service_minutes': round(totals['service_minutes']),
            'waiting_minutes': round(totals['waiting_minutes']),
            'break_minutes': round(totals['break_minutes']),
            'total_minutes': round(total_minutes),
            'start_time': minutes_to_hhmm(vehicle.shift_start_min),
            'end_time': minutes_to_hhmm(clock),
            'energy': round(totals['energy'], 2),
            'energy_unit': 'kWh' if (vehicle.fuel_type or '').lower() == 'electric' else 'L',
            'estimated_fuel_l': round(totals['energy'], 2),
            'co2_kg': round(totals['co2_kg'], 2),
            'fuel_cost_gbp': round(totals['fuel_cost_gbp'], 2),
            'running_cost_gbp': round(totals['running_cost_gbp'], 2),
            'driver_cost_gbp': round(totals['driver_cost_gbp'], 2),
            'estimated_cost_gbp': round(total_cost, 2),
            'cost_per_km': round(total_cost / distance_km, 2) if distance_km else 0.0,
            'start_load_kg': round(start_load_kg, 2),
            'peak_load_kg': round(peak_load_kg, 2),
            'peak_load_m3': round(peak_load_m3, 3),
            'capacity_kg': vehicle.capacity_kg,
            'capacity_m3': vehicle.capacity_m3,
            'weight_utilisation_pct': round(min(utilisation_kg, 999), 1),
            'volume_utilisation_pct': round(min(utilisation_m3, 999), 1),
        },
    }


def _has_matching_pickup(stops: List[Stop], delivery: Stop) -> bool:
    return any(s.type == 'pickup' and s.order_id and s.order_id == delivery.order_id for s in stops)


def _over_capacity(vehicle: Vehicle, load_kg, load_m3, pallets) -> bool:
    if vehicle.capacity_kg and load_kg - vehicle.capacity_kg > 1e-6:
        return True
    if vehicle.capacity_m3 and load_m3 - vehicle.capacity_m3 > 1e-6:
        return True
    if vehicle.max_pallets and pallets > vehicle.max_pallets:
        return True
    return False


def _infeasible(vehicle: Vehicle, reason: str) -> dict:
    return {'feasible': False, 'vehicle_id': vehicle.id, 'vehicle_name': vehicle.name, 'reason': reason}


# --------------------------------------------------------------------------
# Objective
# --------------------------------------------------------------------------

def route_objective(result: dict, preference: str) -> float:
    """Scalar score for a costed route — lower is better."""
    if not result.get('feasible'):
        return float('inf')
    m = result['metrics']
    late = sum(1 for v in result.get('violations', []) if v['type'] == 'time_window')
    penalty = late * 50.0
    if preference == 'fastest':
        return m['total_minutes'] + m['empty_km'] * 0.2 + penalty
    if preference == 'cheapest':
        return m['estimated_cost_gbp'] + m['empty_km'] * 0.1 + penalty
    # greenest (default): CO2 first, with empty running penalised hard
    return m['co2_kg'] * 3.0 + m['empty_km'] * 0.5 + m['total_distance_km'] * 0.1 + penalty


# --------------------------------------------------------------------------
# Construction + local search
# --------------------------------------------------------------------------

def _precedence_ok(stops: List[Stop]) -> bool:
    seen_pickup = set()
    for stop in stops:
        if stop.type == 'pickup' and stop.order_id:
            seen_pickup.add(stop.order_id)
        elif stop.type == 'delivery' and stop.order_id:
            has_pickup = any(s.type == 'pickup' and s.order_id == stop.order_id for s in stops)
            if has_pickup and stop.order_id not in seen_pickup:
                return False
    return True


def _precedence_pairs(stops: List[Stop]) -> List[Tuple[int, int]]:
    """(pickup_index, delivery_index) for every order present in the route."""
    pickups, deliveries = {}, {}
    for index, stop in enumerate(stops):
        if not stop.order_id:
            continue
        if stop.type == 'pickup':
            pickups[stop.order_id] = index
        elif stop.type == 'delivery':
            deliveries[stop.order_id] = index
    return [(pickups[order], deliveries[order]) for order in pickups if order in deliveries]


def _relocate_ok(stops: List[Stop], source: int, target: int) -> bool:
    """Would moving stops[source] to position `target` keep pickup before drop?"""
    stop = stops[source]
    if stop.type not in ('pickup', 'delivery') or not stop.order_id:
        return True
    wanted = 'delivery' if stop.type == 'pickup' else 'pickup'
    partner = next((i for i, s in enumerate(stops)
                    if s.order_id == stop.order_id and s.type == wanted), None)
    if partner is None:
        return True
    partner_after = partner if partner < source else partner - 1
    return target < partner_after if stop.type == 'pickup' else target > partner_after


def _reversal_ok(pairs: List[Tuple[int, int]], start: int, end: int) -> bool:
    """A 2-opt reversal is only valid if it does not flip a pickup/delivery pair."""
    return not any(start <= pickup < end and start <= delivery < end for pickup, delivery in pairs)


def _end_node(vehicle: Vehicle, options: PlanOptions) -> Optional[Stop]:
    if vehicle.end:
        return vehicle.end
    return vehicle.start if options.return_to_start and vehicle.return_to_start else None


def _insertion_deltas(vehicle: Vehicle, stops: List[Stop], stop: Stop,
                      provider: DistanceProvider, options: PlanOptions,
                      first_index: int = 0) -> List[Tuple[float, int]]:
    """Extra distance for inserting `stop` at each position — O(1) per position.

    Full route evaluation is far too expensive to run for every candidate
    position (it builds a whole timeline); this cheap detour cost is used to
    shortlist positions, and only the shortlist is evaluated properly.
    """
    end = _end_node(vehicle, options)
    nodes = [vehicle.start] + stops
    deltas = []
    for index in range(first_index, len(stops) + 1):
        previous = nodes[index]
        following = stops[index] if index < len(stops) else end
        if following is None:                       # appending with no return leg
            delta = provider.leg(previous, stop)[0]
        else:
            delta = (provider.leg(previous, stop)[0] + provider.leg(stop, following)[0]
                     - provider.leg(previous, following)[0])
        deltas.append((delta, index))
    deltas.sort(key=lambda item: item[0])
    return deltas


def _candidate_routes(vehicle: Vehicle, stops: List[Stop], job: Job,
                      provider: DistanceProvider, options: PlanOptions) -> List[List[Stop]]:
    """Shortlist of candidate stop sequences for adding `job` to a route."""
    width = max(1, options.insertion_width)

    if job.pickup is None or job.delivery is None:
        stop = job.delivery or job.pickup
        return [
            stops[:index] + [stop] + stops[index:]
            for _, index in _insertion_deltas(vehicle, stops, stop, provider, options)[:width * 2]
        ]

    candidates = []
    for _, pickup_index in _insertion_deltas(vehicle, stops, job.pickup, provider, options)[:width]:
        with_pickup = stops[:pickup_index] + [job.pickup] + stops[pickup_index:]
        for _, delivery_index in _insertion_deltas(
                vehicle, with_pickup, job.delivery, provider, options,
                first_index=pickup_index + 1)[:width]:
            candidates.append(
                with_pickup[:delivery_index] + [job.delivery] + with_pickup[delivery_index:])
    return candidates


def plan(vehicles: List[Vehicle], jobs: List[Job], extra_stops: List[Stop],
         options: PlanOptions, provider: Optional[DistanceProvider] = None) -> dict:
    """Assign jobs to vehicles and sequence each vehicle's stops."""
    provider = provider or DistanceProvider(options.road_factor)
    if not vehicles:
        return {'vehicles': [], 'unassigned': [
            {'order_id': j.order_id, 'reference': j.reference, 'reason': 'No vehicle available'} for j in jobs
        ], 'summary': _summarise([], jobs)}

    routes: Dict[str, List[Stop]] = {v.id: [] for v in vehicles}
    vehicles_by_id = {v.id: v for v in vehicles}
    unassigned: List[dict] = []

    # Locked mode: visit the stops exactly in the order they were given.
    if not options.optimize_sequence:
        return _plan_locked(vehicles, jobs, extra_stops, options, provider)

    # Physical custom stops (rest/fuel/waypoints) are placed first so the
    # optimiser routes deliveries around them.
    for stop in extra_stops:
        target = stop.vehicle_id if stop.vehicle_id in routes else vehicles[0].id
        routes[target].append(stop)

    deadline = time.monotonic() + max(1.0, options.time_budget_seconds)

    # --- construction: hardest jobs first, cheapest feasible insertion
    ordered_jobs = sorted(jobs, key=lambda j: (j.priority, -j.weight_kg, -j.volume_m3))
    for job in ordered_jobs:
        best = None
        candidate_vehicles = (
            [vehicles_by_id[job.vehicle_id]] if job.vehicle_id in vehicles_by_id else vehicles
        )
        for vehicle in candidate_vehicles:
            if job.temperature_controlled and not vehicle.temperature_controlled:
                continue
            current = routes[vehicle.id]
            base_score = (route_objective(evaluate_route(vehicle, current, provider, options),
                                          options.preference) if current else 0.0)
            for candidate in _candidate_routes(vehicle, current, job, provider, options):
                if not _precedence_ok(candidate):
                    continue
                result = evaluate_route(vehicle, candidate, provider, options)
                if not result.get('feasible'):
                    continue
                score = route_objective(result, options.preference) - base_score
                if best is None or score < best[0]:
                    best = (score, vehicle.id, candidate)
        if best is None:
            reason = 'No vehicle has the capacity (or equipment) for this order'
            if job.temperature_controlled:
                reason = 'No temperature-controlled vehicle available with spare capacity'
            unassigned.append({'order_id': job.order_id, 'reference': job.reference, 'reason': reason})
        else:
            routes[best[1]] = best[2]

    # --- improvement (best-effort within the remaining time budget)
    for vehicle in vehicles:
        routes[vehicle.id] = _local_search(vehicle, routes[vehicle.id], provider, options, deadline)

    results = []
    for vehicle in vehicles:
        stops = routes[vehicle.id]
        if not stops:
            continue
        result = evaluate_route(vehicle, stops, provider, options)
        if result.get('feasible'):
            results.append(result)
        else:
            for stop in stops:
                if stop.order_id:
                    unassigned.append({'order_id': stop.order_id, 'reference': stop.order_ref,
                                       'reason': result.get('reason', 'Route infeasible')})

    return {'vehicles': results, 'unassigned': unassigned, 'summary': _summarise(results, jobs, unassigned)}


def _plan_locked(vehicles: List[Vehicle], jobs: List[Job], extra_stops: List[Stop],
                 options: PlanOptions, provider: DistanceProvider) -> dict:
    """Plan without re-ordering: stops are visited in the order they arrived.

    Stops are grouped by their `vehicle_id` when one is set, otherwise they all
    ride on the first vehicle — with a locked sequence there is nothing for the
    optimiser to split across a fleet.
    """
    all_stops = [stop for job in jobs for stop in job.stops] + list(extra_stops)
    all_stops.sort(key=lambda stop: stop.sequence)

    routes: Dict[str, List[Stop]] = {vehicle.id: [] for vehicle in vehicles}
    for stop in all_stops:
        target = stop.vehicle_id if stop.vehicle_id in routes else vehicles[0].id
        routes[target].append(stop)

    results, unassigned = [], []
    for vehicle in vehicles:
        stops = routes[vehicle.id]
        if not stops:
            continue
        # Capacity is reported as a violation here rather than dropping work:
        # the planner asked for this exact sequence and needs to see why it fails.
        relaxed = replace(options, enforce_capacity=False)
        result = evaluate_route(vehicle, stops, provider, relaxed)
        if not result.get('feasible'):
            unassigned.extend({'order_id': stop.order_id, 'reference': stop.order_ref,
                               'reason': result.get('reason', 'Sequence not feasible')}
                              for stop in stops if stop.order_id)
            continue
        strict = evaluate_route(vehicle, stops, provider, options)
        if not strict.get('feasible'):
            result.setdefault('violations', []).append({
                'type': 'capacity', 'stop': None, 'order_ref': None,
                'message': strict.get('reason', 'Load exceeds the vehicle capacity'),
            })
        if not _precedence_ok(stops):
            result.setdefault('violations', []).append({
                'type': 'precedence', 'stop': None, 'order_ref': None,
                'message': 'A delivery is sequenced before its pickup',
            })
        results.append(result)

    return {'vehicles': results, 'unassigned': unassigned,
            'summary': _summarise(results, jobs, unassigned)}


def _route_distance(vehicle: Vehicle, stops: List[Stop], provider: DistanceProvider,
                    options: PlanOptions) -> float:
    """Total driving distance of a sequence — the cheap proxy used for pruning."""
    if not stops:
        return 0.0
    total = 0.0
    cursor = vehicle.start
    for stop in stops:
        total += provider.leg(cursor, stop)[0]
        cursor = stop
    end = _end_node(vehicle, options)
    if end is not None:
        total += provider.leg(cursor, end)[0]
    return total


def _local_search(vehicle: Vehicle, stops: List[Stop], provider: DistanceProvider,
                  options: PlanOptions, deadline: Optional[float] = None) -> List[Stop]:
    """Or-opt (relocate) + 2-opt passes, precedence-safe.

    Candidate moves are ranked by their distance delta (cheap) and only the most
    promising ones are scored with a full route evaluation (expensive). Without
    that split a 40-order plan takes minutes; with it, seconds.
    """
    if len(stops) < 3:
        return stops

    best = stops
    best_score = route_objective(evaluate_route(vehicle, best, provider, options), options.preference)
    verify_budget = max(4, options.verify_per_pass)

    for _ in range(max(1, options.local_search_rounds)):
        if deadline and time.monotonic() > deadline:
            break

        base_distance = _route_distance(vehicle, best, provider, options)
        pairs = _precedence_pairs(best)
        moves = []

        # relocate one stop elsewhere in the route
        for i in range(len(best)):
            without = best[:i] + best[i + 1:]
            without_distance = _route_distance(vehicle, without, provider, options)
            for delta, j in _insertion_deltas(vehicle, without, best[i], provider, options):
                if j == i or without_distance + delta >= base_distance - 1e-6:
                    continue
                # Precedence is checked here, before ranking: the shortest moves
                # are usually the invalid ones (a drop pulled ahead of its
                # pickup), and ranking them would crowd out every valid move.
                if not _relocate_ok(best, i, j):
                    continue
                moves.append((without_distance + delta, without[:j] + [best[i]] + without[j:]))

        # 2-opt: reverse a segment
        for i in range(len(best) - 1):
            for j in range(i + 2, len(best) + 1):
                if not _reversal_ok(pairs, i, j):
                    continue
                candidate = best[:i] + list(reversed(best[i:j])) + best[j:]
                candidate_distance = _route_distance(vehicle, candidate, provider, options)
                if candidate_distance < base_distance - 1e-6:
                    moves.append((candidate_distance, candidate))

        moves.sort(key=lambda move: move[0])
        improved = False
        for _, candidate in moves[:verify_budget]:
            if deadline and time.monotonic() > deadline:
                break
            if not _precedence_ok(candidate):
                continue
            result = evaluate_route(vehicle, candidate, provider, options)
            score = route_objective(result, options.preference)
            if score < best_score - 1e-6:
                best, best_score, improved = candidate, score, True
                break     # restart the pass from the improved route

        if not improved:
            break
    return best


def _summarise(results: List[dict], jobs: List[Job], unassigned: Optional[List[dict]] = None) -> dict:
    unassigned = unassigned or []
    totals = {
        'vehicles_used': len(results),
        'orders_planned': len(jobs) - len(unassigned),
        'orders_unassigned': len(unassigned),
        'total_stops': sum(r['metrics']['total_stops'] for r in results),
        'total_distance_km': round(sum(r['metrics']['total_distance_km'] for r in results), 2),
        'total_distance_miles': round(sum(r['metrics']['total_distance_miles'] for r in results), 2),
        'empty_km': round(sum(r['metrics']['empty_km'] for r in results), 2),
        'empty_miles': round(sum(r['metrics']['empty_miles'] for r in results), 2),
        'loaded_km': round(sum(r['metrics']['loaded_km'] for r in results), 2),
        'total_minutes': round(sum(r['metrics']['total_minutes'] for r in results)),
        'driving_minutes': round(sum(r['metrics']['driving_minutes'] for r in results)),
        'co2_kg': round(sum(r['metrics']['co2_kg'] for r in results), 2),
        'estimated_fuel_l': round(sum(r['metrics']['estimated_fuel_l'] for r in results), 2),
        'estimated_cost_gbp': round(sum(r['metrics']['estimated_cost_gbp'] for r in results), 2),
        'violations': sum(len(r.get('violations', [])) for r in results),
    }
    total = totals['total_distance_km']
    totals['empty_pct'] = round((totals['empty_km'] / total * 100) if total else 0.0, 1)
    if results:
        totals['avg_weight_utilisation_pct'] = round(
            sum(r['metrics']['weight_utilisation_pct'] for r in results) / len(results), 1)
        totals['avg_volume_utilisation_pct'] = round(
            sum(r['metrics']['volume_utilisation_pct'] for r in results) / len(results), 1)
    else:
        totals['avg_weight_utilisation_pct'] = 0.0
        totals['avg_volume_utilisation_pct'] = 0.0
    return totals


def plan_fixed_sequence(vehicle: Vehicle, stops: List[Stop], options: PlanOptions,
                        provider: Optional[DistanceProvider] = None) -> dict:
    """Cost a hand-ordered sequence (used by the drag-to-reorder planner UI)."""
    provider = provider or DistanceProvider(options.road_factor)
    result = evaluate_route(vehicle, stops, provider, options)
    if result.get('feasible') and not _precedence_ok(stops):
        result.setdefault('violations', []).append({
            'type': 'precedence', 'stop': None, 'order_ref': None,
            'message': 'A delivery is sequenced before its pickup',
        })
    return result
